import "./globals.css";
import { Inter } from "next/font/google";
// Components
import { Header } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextJS Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <div className="max-w-[968px] mx-auto px-4">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
